//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagerSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesManagerSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair do sistema?.
        /// </summary>
        internal static string MESSAGE_EXIT_SYSTEM {
            get {
                return ResourceManager.GetString("MESSAGE_EXIT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos usuário e senha devem ser preenchidos!.
        /// </summary>
        internal static string MESSAGE_LOGIN_VOID {
            get {
                return ResourceManager.GetString("MESSAGE_LOGIN_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha obrigatória!.
        /// </summary>
        internal static string MESSAGE_PASSWORD_VOID {
            get {
                return ResourceManager.GetString("MESSAGE_PASSWORD_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário e/ou senha inválida!.
        /// </summary>
        internal static string MESSAGE_USER_INVALID {
            get {
                return ResourceManager.GetString("MESSAGE_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário obrigatório!.
        /// </summary>
        internal static string MESSAGE_USER_VOID {
            get {
                return ResourceManager.GetString("MESSAGE_USER_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção!.
        /// </summary>
        internal static string MESSAGE_WARNING {
            get {
                return ResourceManager.GetString("MESSAGE_WARNING", resourceCulture);
            }
        }
    }
}
